title: "16752plus1"
description: "记录学习、想法和研究笔记"
author: "16752plus1"
url: "https://16752plus1.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

permalink: /:year/:month/:day/:title/
